version: "3.9"

services:

  petio:
    image: ghcr.io/petio-team/petio:latest
    container_name: petio
    hostname: petio
    ports:
      - "7777:7777"
    networks:
      - private
    depends_on:
      - mongo
    user: "1000:1000"
    environment:
      - TZ=$tzone
    volumes:
      - ${app_data}/petio:/app/api/config
      - ${app_data}/petio/logs:/app/logs
    restart: unless-stopped
  mongo:
    image: mongo
    container_name: mongo
 #   entrypoint: ["db.adminCommand( { setFeatureCompatibilityVersion: "6.0" } )"]
    hostname: mongo
    ports:
      - "27017:27017"
    networks:
      - private
    user: "1000:1000"
    volumes:
      - ${app_data}/mongo:/data/db
    restart: unless-stopped

networks:
  private:
    driver: bridge
#    external: true